### ISSUE TITLE
Add an example of error management in the README.md

### ISSUE THREAD

**Issue by Oxwee** [Sento/modal-responder-rails#1]
How to handle an error? For example, I am using a remote modal for the login and user's input is incorrect. Then I want to stay on the same page and show an error message but still allow the user to enter a new values. Since you are rendering a controller layout how do you handle `redirect_to`? Also, same problem with additional `JavaScript`, using this modal gem you are not allowed to use javascript inside the modal...

**Comment by zedtux** [comment]
Thank you @Oxwee for your issue.

All depends on the way you're building your application. In my case, I'm using JavaScript only, not HTML calls, so `redirect_to` can't work, but `window.location.href = '<path-here>'` will.
But in the case of JavaScript, you don't really want to redirect the users somewhere (excepted in certain cases), but you want to :

- Show errors if any
- Hide the modal if all is fine
- Refresh the list/page where the user is with the new data

To do so, and as I'm using Ajax (`form_for` with `remote: true`), submitting the form will call the `form_for` action which is handled by a controller.
In this controller, I'm doing my stuff (finding/building a new object, updating attributes and so on), and then I'm using a `respond_to` block with a `format.js`.
This will tell Rails to look for a `<action-name>.js.erb` file which will contains the logique described above.

The `<action-name>.js.erb` is a mixture of Ruby code and JavaScript code. I'm checking for errors in my object, if none then I hide the modal, and refresh what shall be refreshed, otherwise if there are errors, I'm looping on the object's errors using JavaScript I'm targeting the field of the error's attribute and assign the bootstrap classes to make it red, and add the error message.

That way you manage the errors in the modal (don't close it until the object is valid) and you also manage the page updates.

Tell me if I'm wrong, but I think the title of your issue should be "Add an example of error management in the README.md"?

Tell me if this is clear enough for you and if you can make it working on your side. If you do so, feel free to open a PR with the `README.md` file updated with the information you are missing right now, so that the next guy will like to find this information.

And sorry for not having described this in the `README.md` file.

**Comment by Oxwee** [comment]
@zedtux Thank you very much for your quick respond. To be honest, I am new in Rails and this is all new to me. I've already asked a question on [https://stackoverflow.com/questions/48009061/reusable-remote-modal-rails](StackOverflow) where I am showing my code and my problem. 

I will think about your answer. Thank you very much for your help and time!

**Comment by zedtux** [comment]
You're welcome @Oxwee and welcome to the RoR world :)

My comment contains all you need so that you should be able to fix your issue. In your SO question, I see you're showing the modal javascript code and the modal responder ruby code.
Just to be sure, all this code is already in this gem, you don't need to add it to your project.

One more thing: When you set `remote: true` in a form, in the controller doing `redirect_to ...` will have no effect as `remote: true` will tell your web browser to use Ajax, and when you do so, you're posting your request as a Javascript request, not an HTML request, which means your web browser will execute the body of the response as a JavaScript code (that's why you have to have a `.js.erb` file which will be the content of the response's body.

If you need more information, feel free to ask here.

P.S: You should update your SO question title, it isn't clear enough.

**Comment by Oxwee** [comment]
Thank you very much for your help. I will try to fix everything and also rename SO question name. Really really appreciate.

**Comment by Oxwee** [comment]
One more question, why does my jQuery autocomplete not working? When I open my model, I can add a new book, but none of my javascript work. As soon as I submit an error, the model will redirect me to another `new` action where all of my javascript works fine..

Do I have to define it somewhere in my `new.js.erb`?

Sorry for all of these questions, but I really want to understand what I am doing.

**Comment by zedtux** [comment]
This is because of the `render :new` when `@book.save` return `false` in your `create` action.

You should remove it, and add the `respond_to` block after your `if`:

```ruby
class BooksController < ApplicationController
  ...
  def create
    ...
    if @book.save
      ...
    end

    respond_to do |format|
      format.js
    end
  end
end
```

This will tell Rails to look for a `app/views/books/create.js.erb` file where you'll do all the Javascript code which will check the errors and show them, or hide the modal and refresh the book list.

**Comment by Oxwee** [comment]
Finally works perfect! Thank you very much @zedtux ! Literally saved my nerves and life.

**Comment by zedtux** [comment]
Nice to read that!! 👍

**Comment by zedtux** [comment]
Don't forget to update your SO question. You can also open a PR on this repo with an update in the `README.md` file :)
